basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: Backend Team
    url: http://example.com/support
  description: API для студента. Доступны только свои данные. Все эндпоинты защищены
    Bearer JWT.
  license:
    name: Internal Use Only
    url: '-'
  termsOfService: http://example.com/terms/
  title: Платформа «Молодёжь» — Студенческая часть (прототип)
  version: 0.1.0
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Авторизация и получение JWT-токена
      parameters:
      - description: Данные для входа
        in: body
        name: body
        required: true
        schema:
          properties:
            login:
              type: string
            password:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              token:
                type: string
              user:
                type: object
            type: object
        "401":
          description: Unauthorized
          schema:
            properties:
              message:
                type: string
            type: object
      summary: Вход студента
      tags:
      - auth
  /challenges/my:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              properties:
                id:
                  type: string
                progress:
                  type: number
                status:
                  type: string
                title:
                  type: string
              type: object
            type: array
      security:
      - BearerAuth: []
      summary: Список личных вызовов
      tags:
      - challenges
  /profile:
    get:
      description: Возвращает данные профиля
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              firstName:
                type: string
              group:
                type: string
              id:
                type: string
              lastName:
                type: string
              segment:
                type: string
              semester:
                type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            properties:
              message:
                type: string
            type: object
      security:
      - BearerAuth: []
      summary: Получить профиль текущего студента
      tags:
      - profile
schemes:
- http
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
